#!/bin/bash
reset
set -x
make clean &>/dev/null
NAME=`uname -m`
unset CFLAGS
MAKE_TARGET=Makefile.Pi.OLED
set -e

TGT_ARCH=arm-linux-gnueabihf
if [ "$1" == "--Debug" ]; then
    CFLAGS='-O0 -ggdb '
fi

if [ "$NAME" == "x86_64" ]; then

    SYSROOT=/home/dwade/remote.root

    [[ -d ${SYSROOT} ]] || mkdir -p ${SYSROOT} 
    
    if [ ! -d ${SYSROOT}/lib ]; then
        echo "need to mount pi root"
        sudo mount whitebox:/ ${SYSROOT}
    fi

    export PATH=/home/dwade/x-tools/arm-linux-gnueabihf/bin:$PATH

    export CXX=`which arm-linux-gnueabihf-g++` 
    export LD=`which arm-linux-gnueeabihf-c++`

    export CFLAGS=" $CFLAGS --sysroot=${SYSROOT} "
    
    export CXXFLAGS=$CFLAGS
    
    LDFLAGS="-L${SYSROOT}/usr/lib/gcc/arm-linux-gnueabihf/10 -L${SYSROOT}/usr/lib  -L${SYSROOT}/usr/lib/$TGT_ARCH -Wl,--sysroot=${SYSROOT} --sysroot=${SYSROOT} "
    #LDFLAGS+="-Wl,--verbose "
    export LDFLAGS 

    make -f $MAKE_TARGET VERBOSE=1  all | tee make.log
    ret=${PIPESTATUS[0]}
    if [ $ret != 0 ]; then
        RED "\nmake failed \n"
        exit
    fi
    xcp-whitebox .
    rm *.o || true

    GREEN "\n make passed local drive cleaned up\n"
else
     rm *.o || true
     echo
     LOG_ROOT="/home/dwade/logs"
     mkdir -p  $LOG_ROOT || true
     sudo cp MMDVM.ini /etc

     make -f $MAKE_TARGET CFLAGS="$CFLAGS" CXXFLAGS="$CFLAGS" SHELL='/bin/bash -x' -j3

    if [ $? == 0 ]; then
        sudo make -f $MAKE_TARGET CFLAGS="$CFLAGS" CXXFLAGS="$CFLAGS" SHELL='/bin/bash -x' install 
        sudo make -f $MAKE_TARGET /etc/MMDVM.ini
        ls -al MMDVMHost
        GREEN "make install paseed"
        rm *.o
#        setup-service --stop
#        setup-service --disable
#        sudo make uninstall-service
#        echo
#        sudo make install
#        sudo make install-service
#        echo
#        ls -al `which MMDVMHost`
#        echo
#        setup-service --enable
#        setup-service --start
#        ./setup-service
    else
        RED "make failed"
    fi
fi
YELLOW "see also make install-service"
YELLOW "         make uninstall-service"
echo
ps -ef | grep -v grep | grep mmdvm*



