#!/bin/bash
reset
make clean &>/dev/null
NAME=`uname -m`

TGT_ARCH=arm-linux-gnueabihf

if [ "$NAME" == "x86_64" ]; then

    SYSROOT=/home/dwade/remote.root

    [[ -d ${SYSROOT} ]] || mkdir -p ${SYSROOT} 
    
    if [ ! -d ${SYSROOT}/lib ]; then
        echo "need to mount pi root"
        sudo mount whitebox:/ ${SYSROOT}
    fi

    export PATH=/home/dwade/x-tools/arm-linux-gnueabihf/bin:$PATH

    export CXX=`which arm-linux-gnueabihf-g++` 
    export LD=`which arm-linux-gnueeabihf-c++`

    export CFLAGS="--sysroot=${SYSROOT} "
    
    export CXXFLAGS=$CFLAGS
    
    LDFLAGS="-L${SYSROOT}/usr/lib/gcc/arm-linux-gnueabihf/10 -L${SYSROOT}/usr/lib  -L${SYSROOT}/usr/lib/$TGT_ARCH -Wl,--sysroot=${SYSROOT} --sysroot=${SYSROOT} "
    #LDFLAGS+="-Wl,--verbose "
    export LDFLAGS 

    make VERBOSE=1  all | tee make.log
    ret=${PIPESTATUS[0]}
    if [ $ret != 0 ]; then
        RED "\nmake failed \n"
        exit
    fi
    xcp-whitebox .
    rm *.o
    GREEN "\n make passed local drive cleaned up\n"
else
    SHELL='/bin/bash -x' make SHELL='/bin/bash -x' -j3
    if [ $? == 0 ]; then
        rm *.o
        ./runit
    fi
fi
YELLOW "see also make install-service"
YELLOW "         make uninstall-service"

