#!/bin/bash

while [ true ]; do

    if [ "$1" == "--stop" ]; then
        systemctl stop mmdvmhost.service
    
    elif [ "$1" == "--start" ]; then
        systemctl daemon-reload
        systemctl start mmdvmhost.service
    
    elif [ "$1" == "--disable" ]; then
        systemctl disable mmdvmhost.service
    
    elif [ "$1" == "--enable" ]; then
        systemctl enable mmdvmhost.service
    else
        echo "runit  --stop|--start| --enable | --disable "
    fi

    shift
    if [ "$1" == "" ]; then 
        break
    fi
done

echo "-----------------------------------------"
systemctl --no-pager  status mmdvmhost.service

echo "-----------------------------------------"
journalctl -u mmdvmhost.service --no-pager

echo "-----------------------------------------"
echo -e "$_REDBLINK"

ps -ef | grep -v "grep" | grep  /usr/local/bin/MMDVMHost
echo -e "$_RESET"

set -x
cat /var/log/mmdvm/*.log

